### PR TITLE
Mdbook

### PR DESCRIPTION
**Pull request by RumovZ**
Not sure how to best structure the page. I think it's nice that the landing page has the warning (sidenote: mdbook doesn't seem to support emojis) and the most recent changes on top. However, the sidebar looks a bit ridiculous as is and specific versions can only be found via search. A toc inside the page, on the other hand, would be really long and require lots of scrolling before the actual content becomes visible.

What do you reckon?

### CODE REVIEW

**Comment by RumovZ** [comment]
As a comprise, maybe we could bundle the notes for smaller releases. Then the sidebar would look like this:
```
Changes
    Changes in 2.1.45
    Changes in 2.1.42 - 2.1.44
    Changes in 2.1.41
    Changes in 2.1.37 - 2.1.40
    ...
Known Issues
```

**Comment by dae** [comment]
How about 10 per section, with a TOC at the top of each? We also https://github.com/ankitects/anki/releases as well as this page, so it's a bit redundant

**Comment by RumovZ** [comment]
Looks much better!
If you wonder about the diff in ec6de50, it's my old nemesis, the line endings.

**Comment by dae** [comment]
Looks good - thank you! The only issue is that the pluses in the filenames might be a problem: https://www.orchidbox.com/google-recommends-avoidance-of-the-plus-sign-in-your-urls#:~:text=Generally%20speaking%2C%20the%20plus%20sign,hence%20causing%20issues%20with%20indexation.

**Comment by dae** [comment]
Thanks Rumo! 🚀

**Pull request merged**
